// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Test.n226589_s_dedikuoti_lt {
    
    
    /// <remarks/>
    [System.Web.Services.WebServiceBinding(Name="ServiceSoap", Namespace="http://rextester.com/")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DoWorkOperationCompleted;
        
        private System.Threading.SendOrPostCallback SumOperationCompleted;
        
        public Service() {
            this.Url = "http://226589.s.dedikuoti.lt/service/Service.asmx";
        }
        
        public Service(string url) {
            this.Url = url;
        }
        
        public event DoWorkCompletedEventHandler DoWorkCompleted;
        
        public event SumCompletedEventHandler SumCompleted;
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rextester.com/DoWork", RequestNamespace="http://rextester.com/", ResponseNamespace="http://rextester.com/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public Result DoWork(string Program, Languages Language, string user, string pass, bool bytes) {
            object[] results = this.Invoke("DoWork", new object[] {
                        Program,
                        Language,
                        user,
                        pass,
                        bytes});
            return ((Result)(results[0]));
        }
        
        public System.IAsyncResult BeginDoWork(string Program, Languages Language, string user, string pass, bool bytes, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("DoWork", new object[] {
                        Program,
                        Language,
                        user,
                        pass,
                        bytes}, callback, asyncState);
        }
        
        public Result EndDoWork(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Result)(results[0]));
        }
        
        public void DoWorkAsync(string Program, Languages Language, string user, string pass, bool bytes) {
            this.DoWorkAsync(Program, Language, user, pass, bytes, null);
        }
        
        public void DoWorkAsync(string Program, Languages Language, string user, string pass, bool bytes, object userState) {
            if ((this.DoWorkOperationCompleted == null)) {
                this.DoWorkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            this.InvokeAsync("DoWork", new object[] {
                        Program,
                        Language,
                        user,
                        pass,
                        bytes}, this.DoWorkOperationCompleted, userState);
        }
        
        private void OnDoWorkCompleted(object arg) {
            if ((this.DoWorkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DoWorkCompleted(this, new DoWorkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rextester.com/Sum", RequestNamespace="http://rextester.com/", ResponseNamespace="http://rextester.com/", ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped, Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        public int Sum(int a, int b) {
            object[] results = this.Invoke("Sum", new object[] {
                        a,
                        b});
            return ((int)(results[0]));
        }
        
        public System.IAsyncResult BeginSum(int a, int b, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Sum", new object[] {
                        a,
                        b}, callback, asyncState);
        }
        
        public int EndSum(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((int)(results[0]));
        }
        
        public void SumAsync(int a, int b) {
            this.SumAsync(a, b, null);
        }
        
        public void SumAsync(int a, int b, object userState) {
            if ((this.SumOperationCompleted == null)) {
                this.SumOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSumCompleted);
            }
            this.InvokeAsync("Sum", new object[] {
                        a,
                        b}, this.SumOperationCompleted, userState);
        }
        
        private void OnSumCompleted(object arg) {
            if ((this.SumCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SumCompleted(this, new SumCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rextester.com/")]
    public enum Languages {
        
        /// <remarks/>
        Java,
        
        /// <remarks/>
        Python,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        CPP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.1433")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://rextester.com/")]
    public partial class Result {
        
        /// <remarks/>
        public string Errors;
        
        /// <remarks/>
        public byte[] Errors_Bytes;
        
        /// <remarks/>
        public string Warnings;
        
        /// <remarks/>
        public byte[] Warnings_Bytes;
        
        /// <remarks/>
        public string Output;
        
        /// <remarks/>
        public byte[] Output_Bytes;
        
        /// <remarks/>
        public string Stats;
        
        /// <remarks/>
        public string Exit_Status;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, DataType="int")]
        public System.Nullable<int> Exit_Code;
        
        /// <remarks/>
        public string System_Error;
    }
    
    public partial class DoWorkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DoWorkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Result Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Result)(this.results[0]));
            }
        }
    }
    
    public delegate void DoWorkCompletedEventHandler(object sender, DoWorkCompletedEventArgs args);
    
    public partial class SumCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SumCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    public delegate void SumCompletedEventHandler(object sender, SumCompletedEventArgs args);
}
